[package]
name = "invaders"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
itertools = "0.12.1"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"